# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default
stages:

# =========================
# STAGE 1 - BUILD & QUALITY
# =========================
- stage: Build
  jobs:
  - job: BuildJob
    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true

    - script: |
        echo "Branch: $(Build.SourceBranch)"
        ls -la
      displayName: "Verify Repo Checkout"

    - script: |
        mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$(SONAR_TOKEN)
      displayName: "Build, Test & Sonar"

    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java'
        failIfCoverageEmpty: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        ArtifactName: 'drop'

- stage: Docker
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DockerJob
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        ls $(System.ArtifactsDirectory)/drop
