# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default
stages:

# =========================
# STAGE 1 - BUILD & QUALITY
# =========================
- stage: Build
  jobs:
  - job: BuildJob
    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true

    - script: |
        echo "Branch: $(Build.SourceBranch)"
        ls -la
      displayName: "Verify Repo Checkout"

    - script: |
        mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$(SONAR_TOKEN)
      displayName: "Build, Test & Sonar"

    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java'
        failIfCoverageEmpty: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        ArtifactName: 'drop'

- stage: Docker
  displayName: "Build & Push Docker Image"
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: DockerJob
    steps:

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Build.SourcesDirectory)'

    - script: |
        ls -la
      displayName: "Verify WAR exists"

    - task: Docker@2
      inputs:
        containerRegistry: 'acr-docker-connection'
        repository: 'demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)


- stage: Deploy
  displayName: "Deploy to AKS"
  dependsOn: Docker
  condition: succeeded()

  jobs:
  - job: DeployJob
    steps:
    - checkout: self
    - task: KubernetesManifest@1
      inputs:
        action: deploy
        kubernetesServiceConnection: 'aks-demo-connection'
        namespace: default
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        containers: |
          demoregistry12345.azurecr.io/demo:$(Build.BuildId)